# Generated by Django 4.2.2 on 2023-06-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season_Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AB', models.IntegerField(default=0)),
                ('BA', models.IntegerField(default=0)),
                ('OBP', models.IntegerField(default=0)),
                ('HR', models.IntegerField(default=0)),
                ('RBI', models.IntegerField(default=0)),
                ('SB', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
                ('H', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='main_app.player')),
            ],
        ),
    ]
