# Generated by Django 4.2.2 on 2023-06-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season_stat',
            options={'ordering': ['year']},
        ),
    ]
