# Generated by Django 4.2.2 on 2023-06-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_season_stat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season_stat',
            old_name='AB',
            new_name='ab',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='BA',
            new_name='ba',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='G',
            new_name='g',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='H',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='HR',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='OBP',
            new_name='obp',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='R',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='RBI',
            new_name='rbi',
        ),
        migrations.RenameField(
            model_name='season_stat',
            old_name='SB',
            new_name='sb',
        ),
    ]
