# Generated by Django 4.2.2 on 2023-06-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_player_season_stat_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season_stat',
            old_name='player_id',
            new_name='player',
        ),
    ]
