# Generated by Django 4.2.2 on 2023-06-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_player_id_season_stat_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('players', models.ManyToManyField(to='main_app.player')),
            ],
        ),
    ]
